#!/command/with-contenv bash
# shellcheck shell=bash

if [[ -z "$SOAPYSAMPLERATE" ]]; then
	echo "SOAPYSAMPLERATE is not set, exiting"
	exit 1
fi

if [[ -z "$GAIN" ]]; then
	echo "GAIN is not set, exiting"
	exit 1
fi

if [[ -z "$GAIN_TYPE" ]]; then
	echo "GAIN_TYPE is not set, exiting"
	exit 1
fi

if [[ -z "$SOAPYSDRDRIVER" ]]; then
	echo "SOAPYSDRDRIVER is not set, exiting"
	exit 1
fi

if [[ -n "${SERVER}" && -z "${SERVER_PORT}" ]]; then
	echo "SERVER is set but SERVER_PORT is not set, exiting"
	exit 1
fi

if [[ -n "$ZMQ_MODE" ]]; then
  if [[ -z "$ZMQ_ENDPOINT" ]]; then
	echo "ZMQ_MODE mode set to '${ZMQ_MODE}, but ZMQ_ENDPOINT is not set, exiting"
	exit 1
  fi
fi

if [[ -n "$ZMQ_ENDPOINT" ]]; then
  if [[ -z "$ZMQ_MODE" ]]; then
    echo "ZMQ_ENDPOINT mode set to '${ZMQ_ENDPOINT}, but ZMQ_MODE is not set, exiting"
	exit 1
  fi
fi

mkdir -p /run/hfdl
touch /run/hfdl/hfdlpast5min.json


# Everything is good to go. Exit with 0

exit 0
