#!/command/with-contenv bash
#shellcheck shell=bash

# Require that hfdl_server is running
if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+0\.0\.0\.0:15556\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
  sleep 1
  if [[ ! ${QUIET_LOGS,,} =~ true ]]; then
    echo "[dumphfdl] hfdl_server not running, exiting"
  fi
  exit
fi
set -e

HFDL_BIN="/usr/local/bin/dumphfdl"
# shellcheck disable=SC2001
FREQ_STRING=""
HFDL_CMD=()

# Specify device ID
if [ -n "${SOAPYSDRDRIVER}" ]; then
  if [ -n "${SOAPYSDRSERIAL}" ]; then
    HFDL_CMD+=("--soapysdr" "driver=${SOAPYSDRDRIVER},serial=${SOAPYSDRSERIAL}")

  else
    HFDL_CMD+=("--soapysdr" "driver=${SOAPYSDRDRIVER}")
  fi
fi

if [ -n "${SOAPYSDRBIAST}" ]; then
  HFDL_CMD+=("--device-settings" "biast_ctrl=true")
fi

HFDL_CMD+=("--sample-rate" "$SOAPYSAMPLERATE")

if [ -z "$GAIN" ]; then
    GAIN="20"
fi

if [ -n "${PPM}" ]; then
	HFDL_CMD+=("--freq-correction" "$PPM")
fi

HFDL_CMD+=("--gain" "$GAIN")

# "--station-id=$FEED_ID"

HFDL_CMD+=("--output" "decoded:json:udp:address=127.0.0.1,port=5556")

if [[ -n "$ZMQ_MODE" ]]; then
  if [[ -n "$ZMQ_ENDPOINT" ]]; then
    HFDL_CMD+=("--output" "decoded:json:zmq:mode=${ZMQ_MODE,,},endpoint=${ZMQ_ENDPOINT}")
  fi
fi

# shellcheck disable=SC2206
HFDL_CMD+=($FREQ_STRING)

echo "[dumphfdl] Starting: '$HFDL_BIN" "${HFDL_CMD[*]}'"

set -eo pipefail

if [[ ${QUIET_LOGS,,} =~ true ]]; then
# shellcheck disable=SC2016
  "$HFDL_BIN" "${HFDL_CMD[@]}" 2>&1 | \
  stdbuf -oL sed --unbuffered '/^$/d' | \
  stdbuf -oL awk '! /^dumphfdl/' | \
  stdbuf -oL awk '! /^Sampling rate set/' | \
  stdbuf -oL awk '! /^Found \[0-9]+ device(s):/' | \
  stdbuf -oL awk '! /^  [0-9]+/' | \
  stdbuf -oL awk '! /^Using device [0-9]+/' | \
  stdbuf -oL awk '! /^Found /' | \
  stdbuf -oL awk '! /^Exact sample rate /' | \
  stdbuf -oL awk '! /^Setting sample rate/' | \
  stdbuf -oL awk '! /PLL not locked!$/' | \
  stdbuf -oL awk '! /^Center frequency set/' | \
  stdbuf -oL awk '! /^Device [#]?[0-9]+/' | \
  stdbuf -oL awk '! /^Allocating [0-9]+ zero-copy buffers/' | \
  stdbuf -oL awk '{print "[dumphfdl] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
  # shellcheck disable=SC2016
  "$HFDL_BIN" "${HFDL_CMD[@]}" 2>&1 | \
  stdbuf -oL sed --unbuffered '/^$/d' | \
  stdbuf -oL awk '{print "[dumphfdl] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
fi

# if we've ended up here there is a problem!
echo "[dumphfdl] Exiting with error"
sleep 5
exit 1
