#!/command/with-contenv bash
#shellcheck shell=bash

set -o pipefail

# Require that hfdl_server is running
if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+0\.0\.0\.0:15556\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
  sleep 1
  if [[ ! ${QUIET_LOGS,,} =~ true ]]; then
    "${s6wrap[@]}" echo "[hfdl_stats] hfdl_server not running, exiting"
  fi
  exit
fi

# Start our stats loop
while true; do

  # capture 5 mins of flows
  "${s6wrap[@]}" timeout --foreground 300s socat -u TCP:127.0.0.1:15556 CREATE:/run/hfdl/hfdl.past5min.json

  # if the port isn't reachable, this file isn't created, either container is shutting down or hfdl_server isn't reachable
  # in both cases let's exit, if this should still be running it will be restarted
  if ! [[ -f /run/hfdl/hfdl.past5min.json ]]; then
    exit
  fi

  # shellcheck disable=SC2016
  "${s6wrap[@]}" echo "$(sed 's/}{/}\n{/g' /run/hfdl/hfdl.past5min.json | wc -l) hfdl messages received in last 5 mins"

  # rotate files keeping last 2 hours
  for i in {24..1}; do
    mv "/run/hfdl/hfdl.$((i-1)).json" "/run/hfdl/hfdl.$i.json" > /dev/null 2>&1 || true
  done
  mv "/run/hfdl/hfdl.past5min.json" "/run/hfdl/hfdl.0.json" > /dev/null 2>&1 || true

  # now check and see if the last 30 minutes of data has any messages. If not, pkill dumphfdl

  # first, verify we have 30 minutes of data by verifying there are at least 6 files
  if [[ $(find /run/hfdl -type f -name 'hfdl.*.json' | wc -l) -gt 6 ]]; then
    # now check the last 6 files for messages
    if [[ $(sed 's/}{/}\n{/g' /run/hfdl/hfdl.{0..5}.json | wc -l) -eq 0 ]]; then
      "${s6wrap[@]}" echo " No messages received in last 30 minutes, killing dumphfdl to rerun the frequency optimizer"
      s6-svc -r /run/service/dumphfdl
      rm -f /run/hfdl/hfdl.*.json
      exit
    fi
  fi

done

sleep 5
